[package]
name = "bin"
publish = false
version = "0.1.0"
edition = "2021"

[dependencies]
glob = "0.3.0"
serde = "1.0"
serde_json = "1.0"
app = { path = "../app" }
migration = { path = "../migration" }
pathdiff = "0.2.1"
syntect = "5.0.0"
lol_html = "0.3.2"
minijinja = "0.31.0"
anyhow = "1.0.69"
sea-orm = { version = "0.11.2", features = ["sqlx-sqlite", "runtime-actix-rustls"] }
async-std = "1.12.0"
