[package]
name = "bin"
publish = false
version = "0.1.0"
edition = "2021"

[dependencies]
glob = "0.3.0"
serde = "1.0"
serde_json = "1.0"
app = { path = "../app" }
rusqlite = { version = "0.28.0", features = ["bundled"] }
pathdiff = "0.2.1"
syntect = "5.0.0"
lol_html = "0.3.2"
minijinja = "0.30.2"
anyhow = "1.0.69"
