[package]
name = "main"
publish = false
version = "0.1.0"
edition = "2021"
default-run = "main"

[dependencies]
actix-files = "0.6.0"
actix-web = { version = "4.0.0", features = ["macros", "compress-brotli"] }
chrono = "0.4.23"
clap = { version = "4.0.29", features = ["derive"] }
env_logger = "0.10"
glob = "0.3.0"
lightningcss = { version = "1.0.0-alpha.16", features = ["grid", "browserslist"] }
minijinja = { version = "0.27.0", features = ["builtins", "debug", "key_interning", "deserialization", "macros", "multi-template", "source"] }
parcel_sourcemap = "2.0.2"
serde = "1.0"
serde_json = "1.0"
swc = "0.238"
swc_common = { version = "0.29", features = ["tty-emitter"] }

[profile.release]
strip = true
