[package]
name = "main"
publish = false
version = "0.1.0"
edition = "2021"
default-run = "main"

[dependencies]
actix-files = "0.6.0"
actix-web = { version = "4.0.0", features = ["macros", "compress-brotli"] }
base64 = "0.13.0"
env_logger = "0.9"
envy = "0.4.2"
glob = "0.3.0"
lightningcss = { version = "1.0.0-alpha.16", features = ["grid", "browserslist"] }
parcel_sourcemap = "2.0.2"
serde = "1.0"
serde_json = "1.0"
swc = "0.229"
swc_common = { version = "0.29", features = ["tty-emitter"] }
tera = { version = "1.17.1", features = ["builtins", "chrono"] }
