[package]
name = "main"
publish = false
version = "0.1.0"
edition = "2021"
default-run = "main"

[dependencies]
actix-files = "0.6.0"
actix-web = { version = "4.0.0", features = ["macros", "compress-brotli"] }
askama = "0.11.1"
base64 = "0.13.0"
chrono = "0.4.0"
derive_more = "0.99"
env_logger = "0.9"
envy = "0.4.2"
glob = "0.3.0"
log = "0.4.16"
minify-html = "0.9.2"
parcel_css = { version = "1.0.0-alpha.16", features = ["grid"] }
parcel_sourcemap = "2.0.2"
serde = "1.0"
serde_json = "1.0"
swc = "0.212"
swc_common = { version = "0.26", features = ["tty-emitter"] }
