[package]
name = "app"
publish = false
version = "0.1.0"
edition = "2021"
default-run = "serve"

[dependencies]
anyhow = "1.0.70"
axum = "0.6.15"
chrono = "0.4.23"
envmnt = "0.10.4"
etag = "4.0.0"
glob = "0.3.0"
log = "0.4.17"
lol_html = "1.0.0"
mime_guess = "2.0.4"
minijinja = { version = "0.33.0", features = ["source"] }
pathdiff = "0.2.1"
sea-orm = { version = "0.11.2", features = ["sqlx-sqlite", "runtime-tokio-rustls"] }
serde = "1.0"
serde_json = "1.0"
syntect = "5.0.0"
tokio = { version = "1.27.0", features = ["macros"] }
tower-http = { version = "0.4.0", features = ["set-header", "compression-gzip", "trace"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

[profile.release]
strip = true
lto = true
