[package]
name = "main"
publish = false
version = "0.1.0"
edition = "2021"
default-run = "main"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = { version = "0.6.0-beta.14", default-features = false }
actix-web = { version = "4.0.0-rc.1", default-features = false, features = ["openssl", "compress-brotli", "macros"] }
dotenv = "0.15.0"
env_logger = "0.9"
handlebars = { version = "4.2.1", features = ["dir_source"] }
minify-html-onepass = "0.8.0"
openssl = { version = "0.10", features = ["v110"] }
parcel_css = "1.0.0-alpha.12"
serde = "1.0"
serde_json = "1.0"
swc = "0.121"
swc_common = { version = "0.17", features = ["tty-emitter"] }
