[package]
name = "main"
publish = false
version = "0.1.0"
edition = "2021"
default-run = "main"

[dependencies]
actix-files = "0.6.0"
actix-web = { version = "4.0.0", features = ["openssl", "compress-brotli", "macros"] }
awc = { version = "3.0.0", features = ["openssl"] }
base64 = "0.13.0"
chrono = "0.4.0"
derive_more = "0.99"
dotenv = { version = "0.15.0", optional = true }
env_logger = "0.9"
log = "0.4.16"
maud = { version = "0.23.0", features = ["actix-web"] }
minify-html-onepass = "0.8.0"
openssl = { version = "0.10", features = ["v110"], optional = true }
parcel_css = { version = "1.0.0-alpha.16", features = ["grid"] }
parcel_sourcemap = "2.0.2"
rss = { version = "2.0", features = ["builders"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
swc = "0.169"
swc_common = { version = "0.17", features = ["tty-emitter"] }

[features]
local = ["openssl", "dotenv"]
