[package]
name = "main"
publish = false
version = "0.1.0"
edition = "2021"
default-run = "main"

[dependencies.actix-files]
version = "0.6.0-beta.14"
default-features = false

[dependencies.actix-web]
version = "4.0.0"
default-features = false
features = ["openssl", "compress-brotli", "macros"]

[dependencies.derive_more]
version = "0.99"
default-features = false

[dependencies.dotenv]
version = "0.15.0"
default-features = false
optional = true

[dependencies.env_logger]
version = "0.9"
default-features = false

[dependencies.maud]
version = "0.23.0"
default-features = false
features = ["actix-web"]

[dependencies.minify-html-onepass]
version = "0.8.0"
default-features = false

[dependencies.openssl]
version = "0.10"
default-features = false
features = ["v110"]
optional = true

[dependencies.parcel_css]
version = "1.0.0-alpha.16"
default-features = false
features = ["grid"]

[dependencies.rand]
version = "0.8"
default-features = false

[dependencies.rss]
version = "2.0"
default-features = false
features = ["builders"]

[dependencies.serde]
version = "1.0"
features = ["derive"]
default-features = false

[dependencies.serde_json]
version = "1.0"
default-features = false

[dependencies.swc]
version = "0.144"
default-features = false

[dependencies.swc_common]
version = "0.17"
default-features = false
features = ["tty-emitter"]

[dependencies.toml]
version = "0.5"
default-features = false

[features]
local = ["openssl", "dotenv"]
