[package]
name = "main"
publish = false
version = "0.1.0"
edition = "2021"
default-run = "main"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.5.0"
actix-web = { version="3.3.2", features = ["openssl"] }
dotenv = "0.15.0"
env_logger = "0.9"
grass = "0.10.8"
lazy_static = "1.4.0"
openssl = { version = "0.10", features = ["v110"] }
pulldown-cmark = { version = "0.9" }
reqwest = { version="0.11.7", features=["blocking"] }
serde = "1.0"
serde_json = "1.0"
swc = { version="0.113", default-features=false }
swc_common = { version="0.17", features=["tty-emitter"] }
tera = "1.15.0"
toml = "0.5.8"
url = "2.2.2"