[package]
name = "main"
publish = false
version = "0.1.0"
edition = "2021"
default-run = "main"

[dependencies]
actix-files = { version = "0.6.0", default-features = false }
actix-web = { version = "4.0.0", features = ["macros", "compress-brotli"], default-features = false }
askama = { version = "0.11.1", default-features = false }
base64 = { version = "0.13.0", default-features = false }
chrono = { version = "0.4.0", default-features = false }
derive_more = { version = "0.99", default-features = false }
env_logger = { version = "0.9", default-features = false }
glob = { version = "0.3.0", default-features = false }
log = { version = "0.4.16", default-features = false }
parcel_css = { version = "1.0.0-alpha.16", features = ["grid"], default-features = false }
parcel_sourcemap = { version = "2.0.2", default-features = false }
serde = { version = "1.0", default-features = false }
serde_json = { version = "1.0", default-features = false }
swc = { version = "0.193", default-features = false }
swc_common = { version = "0.19", features = ["tty-emitter"], default-features = false }
