[package]
name = "main"
publish = false
version = "0.1.0"
edition = "2021"
default-run = "main"

[dependencies.actix-files]
version = "0.6.0-beta.14"
default-features = false

[dependencies.actix-web]
version = "4.0.0-rc.1"
default-features = false
features = ["openssl", "compress-brotli", "macros"]

[dependencies.dotenv]
version = "0.15.0"
default-features = false

[dependencies.env_logger]
version = "0.9"
default-features = false

[dependencies.handlebars]
version = "4.2.1"
default-features = false
features = ["dir_source"]

[dependencies.minify-html-onepass]
version = "0.8.0"
default-features = false

[dependencies.openssl]
version = "0.10"
default-features = false
features = ["v110"]

[dependencies.parcel_css]
version = "1.0.0-alpha.12"
default-features = false
features = ["grid"]

[dependencies.serde_json]
version = "1.0"
default-features = false

[dependencies.swc]
version = "0.123"
default-features = false

[dependencies.swc_common]
version = "0.17"
default-features = false
features = ["tty-emitter"]
