[package]
name = "app"
publish = false
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.70", features = ["backtrace"] }
axum = "0.6.15"
base62 = "2.0.2"
camino = "1.1.4"
chrono = "0.4.23"
clap = { version = "4.3.17", features = ["derive"] }
etag = "4.0.0"
glob = "0.3.0"
hyper = "0.14.27"
log = "0.4.17"
lol_html = "1.0.0"
mime_guess = "2.0.4"
minijinja = { version = "1.0.0", features = ["loader"] }
pathdiff = { version = "0.2.1", features = ["camino"] }
pulldown-cmark = "0.9.3"
sea-orm = { version = "0.12.1", features = [
	"sqlx-sqlite",
	"runtime-tokio-rustls",
] }
serde = "1.0.185"
serde_json = "1.0"
syntect = "5.0.0"
tokio = { version = "1.27.0", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.4.2", features = [
	"set-header",
	"compression-gzip",
	"trace",
] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

[profile.release]
strip = true
lto = true
codegen-units = 1
# opt-level = "s"
