[tasks.watch]
env = {RUST_LOG="serve=debug", RUST_BACKTRACE=1, APP_PORT=3000, APP_DEV=true}
command="cargo"
args=["watch", "-i", "*.css", "-x", "r --bin setup", "-s", "cargo run --no-default-features"]

[tasks.build]
command="docker"
args=["build", ".", "-t", "my-blog"]

[tasks.run]
command="docker"
args=["run", "-p", "3000:8080", "my-blog"]
