[tasks."watch:app"]
env = { RUST_LOG = "serve=debug", RUST_BACKTRACE = 1 }
command = "cargo"
args = [
	"watch",
	"-i",
	"*.css",
	"-x",
	"r --bin setup --no-default-features",
	"-x",
	"r --bin app --no-default-features -- --no-cache --listen 3000",
]

[tasks."watch:style"]
command = "coolstyleserver"

[tasks."docker:build"]
command = "docker"
args = ["build", ".", "-t", "my-blog"]

[tasks."docker:start"]
command = "docker"
args = ["run", "-p", "3000:8080", "--name", "my-blog", "my-blog"]

[tasks."docker:stop"]
command = "docker"
args = ["rm", "-f", "my-blog"]

[tasks.watch]
run_task = { name = ["watch:style", "watch:app"], parallel = true }
