title = "Erick Merchant"
host = "https://erickmerchant.com"
author = "Erick Merchant"
description = "The personal home page of Erick Merchant"
bio = """
Hey there! I'm Erick. I've been making things for the web for 19 years. I like to make things that are fast and efficient. I love Rust, CSS, and a bit of JavaScript. I am currently looking for work, so if you're looking to hire check out my [résumé](/resume/) and let's connect.
"""

[[projects]]
href = "https://github.com/erickmerchant/coolstyleserver"
title = "Cool Style Server"
description = """
A development server that does hot module replacement of CSS without using a JavaScript bundler. You shouldn't need NPM to design a website.
"""

[[projects]]
href = "https://github.com/erickmerchant/handcraft"
title = "Handcraft"
description = """
A front-end framework using a fluent interface for creating reactive UI.
"""

[[projects]]
href = "/projects/memory/"
title = "Memory"
description = """
A game I made for my daughter to play when she wants to see my phone. The app is written in Handcraft. Halloween version [here](/projects/memory/halloween.html)
"""
