title = "ErickMerchant.com"
base = "https://erickmerchant.com"
description = "The personal site of Erick Merchant."
copyright = "© 2022 Erick Merchant"

[[links]]
href = "/"
title = "Home"

[[links]]
href = "/minefield/start.html"
title = "Minefield"

[[links]]
href = "https://github.com/erickmerchant/my-blog"
title = "View Source"
