[package]
name = "scripts"
publish = false
version = "0.1.0"
edition = "2021"

[dependencies]
glob = "0.3.0"
serde = "1.0"
serde_json = "1.0"
schema = { path = "../schema" }
rusqlite = "0.28.0"
pathdiff = "0.2.1"
