[package]
name = "scripts"
publish = false
version = "0.1.0"
edition = "2021"

[dependencies]
glob = "0.3.0"
serde = "1.0"
serde_json = "1.0"
models = { path = "../models" }
rusqlite = { version = "0.28.0", features = ["bundled"] }
pathdiff = "0.2.1"
